config/routes.rb
Rails.application.routes.draw do

root 'user#index'

get 'user/index'
get 'user/consult_api'
get 'user/erase_db'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  paginates_per 9
  mount_uploader :avatar, AvatarUploader
  validates_uniqueness_of :first_name, scope: :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
    if params[:query].present?
      sql_query = "first_name ILIKE :query OR last_name ILIKE :query"
      @users = User.where(sql_query, query: "%#{params[:query]}%").page params[:page]
    else
       @users = User.all.order(:first_name).page params[:page]
    end
  end

  def consult_api
    response =  RestClient.get "https://randomuser.me/api/?results=1000&seed=giga&nat=br" #consult the API with seed = giga & 30 results & nationality = br
    byebugs
    repos = JSON.parse(response) # "parse das informações em JSON
    repos["results"].each do |result| #create a new instance of the model user
      #byebug
      search = User.where(first_name: "#{result["name"]["first"]}" , last_name: "#{result["name"]["last"]}")
      if search.count == 0
        user = User.new
        user.genre = result["gender"] #select gender
        if user.genre == "male"
          user.genre = "masculino"
          else
          user.genre = "feminino"
        end
        user.title = result["name"]["title"] #select title
        user.first_name = result["name"]["first"] #select first name
        user.last_name = result["name"]["last"] #select last name
        user.email = result["email"] #select email
        user.picture = result["picture"]["large"] #picture address
        user.remote_avatar_url = user.picture #saving picture locally
        user.save!
      end
    end
    redirect_to action:'index'
  end

  def erase_db
    User.all.each do |user|
      user.remove_avatar!
      user.save!
      user.delete
    end
    redirect_to action:'index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="Teste Gigaservice" content="Teste do Kauê">
    <meta name="keywords" content="Giga, Rails, API, Gigaservice">
    <meta name="author" content="Kauê Matteucci">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />

     <title>GigaServiceKaue</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
      <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<%= image_tag "kaue.jpg", alt: "Kauê" , :class => "navbar-photo" %>
<h1 class='navbar'> Teste Kauê - Giga Service </h1>

app/views/user/index.html.erb
<div class="container">

  <div class="card-pages">
    <div class= "row">

      <div class="col-12 col-sm-4">
        <%= link_to 'Carregar + 30 registros', user_consult_api_path, method: :get %>
        <br> <%= page_entries_info @users %>
      </div>

      <div class="col-12 col-sm-4">
          <%= form_tag user_index_path, method: :get do %>
          <%= text_field_tag :query, params[:query], class: "form-control",placeholder: "Digite nome ou sobrenome a procurar"%>
        <% end %>
      </div>

    <div class="col-12 col-sm-4">
      <%= link_to 'Apagar dados', user_erase_db_path, method: :get %>
        <br> <%= paginate @users %>
    </div>
  </div>
</div>


  <div class="row">
    <% @users.each do |user| %>
      <div class="col-12 col-sm-4">
          <div class="card">
          <p> Nome:
          <%= user.title.capitalize %>
          <%= user.first_name.capitalize %>
          <%= user.last_name.capitalize %> </p>
          <p> Sexo: <%= user.genre %> </p>
          <p> Email: <%= user.email %> </p>
          <p> Imagem: <%= user.avatar.url %> </p>
          <img class="card-user" src="<%= user.avatar %>">
        </div>
      </div>
    <% end %>
  </div>
</div>